//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use faststr::FastStr;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "casbin_rule")]
#[serde(rename_all = "snake_case")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub ptype: FastStr,
    pub v0: FastStr,
    pub v1: FastStr,
    pub v2: FastStr,
    pub v3: FastStr,
    pub v4: FastStr,
    pub v5: FastStr,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
