//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

pub use super::t_cloudnative_phone_dc::Entity as TCloudnativePhoneDc;
pub use super::t_cloudnative_phone_feature_gate::Entity as TCloudnativePhoneFeatureGate;
pub use super::t_cloudnative_phone_pod_info::Entity as TCloudnativePhonePodInfo;
pub use super::t_cloudnative_phone_pod_model_rule_settings::Entity as TCloudnativePhonePodModelRuleSettings;
pub use super::t_cloudnative_phone_product_statistic::Entity as TCloudnativePhoneProductStatistic;
pub use super::user::Entity as User;
