//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use faststr::FastStr;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "t_blog_user")]
#[serde(rename_all = "snake_case")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    #[sea_orm(unique)]
    pub user_id: Option<FastStr>,
    pub nickname: Option<FastStr>,
    #[sea_orm(unique)]
    pub username: Option<FastStr>,
    pub description: Option<FastStr>,
    pub gender: Option<i32>,
    pub password: Option<FastStr>,
    pub avatar: Option<FastStr>,
    pub email: Option<FastStr>,
    pub tel: Option<FastStr>,
    pub addr: Option<FastStr>,
    pub token: Option<FastStr>,
    pub ip: Option<FastStr>,
    pub sign_status: Option<i8>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
