//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "t_cloudnative_phone_pod_model_rule_settings")]
#[serde(rename_all = "snake_case")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub account_id: String,
    pub rule_name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub settings: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub properties: Option<String>,
    pub create_at: DateTimeUtc,
    pub update_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
