//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "t_cloudnative_phone_dc")]
#[serde(rename_all = "snake_case")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    #[sea_orm(unique)]
    pub dc_id: String,
    pub zone_id: String,
    pub volc_region: String,
    pub cube_version: String,
    pub dc_name: String,
    pub region: Option<String>,
    pub province: String,
    pub isp: i32,
    #[sea_orm(column_type = "Decimal(Some((6, 3)))")]
    pub longitude: Decimal,
    #[sea_orm(column_type = "Decimal(Some((6, 3)))")]
    pub latitude: Decimal,
    pub dc_type: i32,
    pub biz: String,
    pub env: String,
    pub supply_policy: String,
    pub allow_ids: Option<String>,
    pub deny_ids: Option<String>,
    pub host: String,
    pub expected_idc: Option<String>,
    pub pod_limit: i32,
    pub pod_real_num: i32,
    pub status: String,
    pub backup_feature: String,
    pub recover_step: i16,
    pub create_at: DateTimeUtc,
    pub update_at: DateTimeUtc,
    pub cilium_network_segment: String,
    pub ct_network_segment: String,
    pub cu_network_segment: String,
    pub cm_network_segment: String,
    pub server_type_code: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
