//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "t_cloudnative_phone_pod_info")]
#[serde(rename_all = "snake_case")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    #[sea_orm(unique)]
    pub pod_id: String,
    pub pod_name: Option<String>,
    pub account_id: String,
    pub product_id: String,
    pub image_id: Option<String>,
    pub image_id_raw: Option<String>,
    pub configuration_code: Option<String>,
    pub display_layout_id: Option<String>,
    pub apk_server: Option<String>,
    pub data_size: Option<i32>,
    pub original_data_size: Option<i32>,
    pub data_size_used: Option<String>,
    pub data_storage_class: Option<String>,
    pub region: Option<String>,
    pub isp: Option<i32>,
    pub dc: Option<String>,
    pub tag_id: Option<String>,
    pub active_status: Option<i32>,
    pub stream_status: Option<i32>,
    pub expect_status: Option<i32>,
    pub online_time: Option<u64>,
    pub create_at: DateTimeUtc,
    pub update_at: DateTimeUtc,
    pub ip: Option<String>,
    pub room_id: Option<String>,
    pub display_status: Option<Json>,
    pub active_status_in_cluster: Option<i32>,
    pub power_on_finish: Option<i64>,
    pub power_off_finish: Option<i64>,
    pub adb_status: Option<i32>,
    pub adb_status_processing: Option<i32>,
    pub adb_expire_time: Option<i64>,
    pub adb: Option<String>,
    pub node_id: Option<String>,
    pub active_id: Option<String>,
    pub schedule_pod_active_id: Option<String>,
    pub data_used: Option<i64>,
    pub resource_version: Option<u64>,
    pub software_version: Option<String>,
    pub firmware_version: Option<String>,
    pub up_bandwidth_limit: Option<i32>,
    pub down_bandwidth_limit: Option<i32>,
    pub ip_white_list: Option<String>,
    pub uid: Option<String>,
    pub persistent_volume_name: Option<String>,
    pub volume_handle: Option<String>,
    pub volume_attributes: Option<Json>,
    pub archive_status: Option<i8>,
    pub prefer_nsid: Option<String>,
    pub custom_route_id: Option<String>,
    pub dns_id: Option<String>,
    pub event_sync_master_id: Option<String>,
    pub event_sync_room_id: Option<String>,
    pub event_sync_status: Option<i32>,
    pub server_type_code: Option<String>,
    pub k8s_resource_type: Option<String>,
    pub storage_type: Option<i32>,
    pub preview_room_id: Option<String>,
    pub preview_stream_provider: Option<String>,
    pub preview_stream_status: Option<i32>,
    pub invalid_action: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
