//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use crate::enumeration;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "user")]
#[serde(rename_all = "snake_case")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub gender: enumeration::Gender,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub name: Option<String>,
    pub email: Option<String>,
    pub age: Option<u8>,
    pub task_scope: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
